name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@1.12.2
    with:
      image-name: devops-tools
      create-artifacts: false
      arm64-build-args: |
        KUBECTL_ARCH=arm64
