name: publish-image

on:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@1.12.3
    with:
      image-name: devops-tools
      arm64-build-args: |
        KUBECTL_ARCH=arm64
    secrets:
      registry-password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
